// Code generated by protoc-gen-gogo.
// source: dockerfile.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	dockerfile.proto

It has these top-level messages:
	ContextRequest
	ContextResponse
*/
package api

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ContextRequest struct {
	SessionID  string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	TarContent []byte `protobuf:"bytes,2,opt,name=tarContent,proto3" json:"tarContent,omitempty"`
}

func (m *ContextRequest) Reset()                    { *m = ContextRequest{} }
func (*ContextRequest) ProtoMessage()               {}
func (*ContextRequest) Descriptor() ([]byte, []int) { return fileDescriptorDockerfile, []int{0} }

type ContextResponse struct {
}

func (m *ContextResponse) Reset()                    { *m = ContextResponse{} }
func (*ContextResponse) ProtoMessage()               {}
func (*ContextResponse) Descriptor() ([]byte, []int) { return fileDescriptorDockerfile, []int{1} }

func init() {
	proto.RegisterType((*ContextRequest)(nil), "dockerfile.v1.ContextRequest")
	proto.RegisterType((*ContextResponse)(nil), "dockerfile.v1.ContextResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DockerfileService service

type DockerfileServiceClient interface {
	SendContext(ctx context.Context, opts ...grpc.CallOption) (DockerfileService_SendContextClient, error)
}

type dockerfileServiceClient struct {
	cc *grpc.ClientConn
}

func NewDockerfileServiceClient(cc *grpc.ClientConn) DockerfileServiceClient {
	return &dockerfileServiceClient{cc}
}

func (c *dockerfileServiceClient) SendContext(ctx context.Context, opts ...grpc.CallOption) (DockerfileService_SendContextClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DockerfileService_serviceDesc.Streams[0], c.cc, "/dockerfile.v1.DockerfileService/SendContext", opts...)
	if err != nil {
		return nil, err
	}
	x := &dockerfileServiceSendContextClient{stream}
	return x, nil
}

type DockerfileService_SendContextClient interface {
	Send(*ContextRequest) error
	CloseAndRecv() (*ContextResponse, error)
	grpc.ClientStream
}

type dockerfileServiceSendContextClient struct {
	grpc.ClientStream
}

func (x *dockerfileServiceSendContextClient) Send(m *ContextRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dockerfileServiceSendContextClient) CloseAndRecv() (*ContextResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ContextResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DockerfileService service

type DockerfileServiceServer interface {
	SendContext(DockerfileService_SendContextServer) error
}

func RegisterDockerfileServiceServer(s *grpc.Server, srv DockerfileServiceServer) {
	s.RegisterService(&_DockerfileService_serviceDesc, srv)
}

func _DockerfileService_SendContext_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DockerfileServiceServer).SendContext(&dockerfileServiceSendContextServer{stream})
}

type DockerfileService_SendContextServer interface {
	SendAndClose(*ContextResponse) error
	Recv() (*ContextRequest, error)
	grpc.ServerStream
}

type dockerfileServiceSendContextServer struct {
	grpc.ServerStream
}

func (x *dockerfileServiceSendContextServer) SendAndClose(m *ContextResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dockerfileServiceSendContextServer) Recv() (*ContextRequest, error) {
	m := new(ContextRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DockerfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dockerfile.v1.DockerfileService",
	HandlerType: (*DockerfileServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendContext",
			Handler:       _DockerfileService_SendContext_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dockerfile.proto",
}

func (m *ContextRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContextRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.SessionID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDockerfile(dAtA, i, uint64(len(m.SessionID)))
		i += copy(dAtA[i:], m.SessionID)
	}
	if len(m.TarContent) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDockerfile(dAtA, i, uint64(len(m.TarContent)))
		i += copy(dAtA[i:], m.TarContent)
	}
	return i, nil
}

func (m *ContextResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContextResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeFixed64Dockerfile(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Dockerfile(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintDockerfile(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ContextRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.SessionID)
	if l > 0 {
		n += 1 + l + sovDockerfile(uint64(l))
	}
	l = len(m.TarContent)
	if l > 0 {
		n += 1 + l + sovDockerfile(uint64(l))
	}
	return n
}

func (m *ContextResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovDockerfile(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDockerfile(x uint64) (n int) {
	return sovDockerfile(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ContextRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ContextRequest{`,
		`SessionID:` + fmt.Sprintf("%v", this.SessionID) + `,`,
		`TarContent:` + fmt.Sprintf("%v", this.TarContent) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ContextResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ContextResponse{`,
		`}`,
	}, "")
	return s
}
func valueToStringDockerfile(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ContextRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDockerfile
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContextRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContextRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDockerfile
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TarContent", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDockerfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDockerfile
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TarContent = append(m.TarContent[:0], dAtA[iNdEx:postIndex]...)
			if m.TarContent == nil {
				m.TarContent = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDockerfile(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDockerfile
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContextResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDockerfile
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContextResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContextResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDockerfile(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDockerfile
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDockerfile(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDockerfile
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDockerfile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDockerfile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDockerfile
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDockerfile
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDockerfile(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDockerfile = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDockerfile   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("dockerfile.proto", fileDescriptorDockerfile) }

var fileDescriptorDockerfile = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xc9, 0x4f, 0xce,
	0x4e, 0x2d, 0x4a, 0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0x12,
	0x29, 0x33, 0x94, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0xcb, 0xe8, 0x83, 0x58, 0x10, 0x45, 0x4a,
	0x91, 0x5c, 0x7c, 0xce, 0xf9, 0x79, 0x25, 0xa9, 0x15, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0xea, 0x5c, 0xec, 0xc5, 0xa9, 0xc5, 0xc5, 0x99, 0xf9, 0x79, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x4e, 0xbc, 0x8f, 0xee, 0xc9, 0x73, 0x06, 0x43, 0x84, 0x3c, 0x5d, 0x82, 0x60, 0xb2,
	0x42, 0x72, 0x5c, 0x5c, 0x25, 0x89, 0x45, 0x60, 0xdd, 0x79, 0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0x48, 0x22, 0x4a, 0x82, 0x5c, 0xfc, 0x70, 0xa3, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x8d, 0x92, 0xb9, 0x04, 0x5d, 0xe0, 0x8e, 0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xf2,
	0xe3, 0xe2, 0x0e, 0x4e, 0xcd, 0x4b, 0x81, 0xaa, 0x15, 0x92, 0xd5, 0x43, 0x71, 0xb7, 0x1e, 0xaa,
	0xf3, 0xa4, 0xe4, 0x70, 0x49, 0x43, 0xac, 0xd0, 0x60, 0x74, 0x92, 0x38, 0xf1, 0x50, 0x8e, 0xe1,
	0xc6, 0x43, 0x39, 0x86, 0x86, 0x47, 0x72, 0x8c, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7,
	0xf8, 0xe0, 0x91, 0x1c, 0x63, 0x12, 0x1b, 0xd8, 0xcf, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x00, 0x5b, 0x75, 0x2c, 0x01, 0x00, 0x00,
}
